import Link from "next/link";
import type { Metadata } from "next";
import { THEME, glow } from "@/lib/theme";

export const metadata: Metadata = {
  title: "HumanizeIt for Students — Bypass GPTZero and Turnitin | HumanizeIt",
  description:
    "Learn how students use HumanizeIt to make AI-assisted writing undetectable by GPTZero and Turnitin. Free plan available. Write naturally, submit confidently.",
  keywords: [
    "humanize AI text",
    "bypass GPTZero",
    "bypass Turnitin",
    "AI detection bypass",
    "student AI writing",
    "undetectable AI",
    "HumanizeIt students",
    "AI text humanizer",
  ],
  openGraph: {
    title: "HumanizeIt for Students — Bypass GPTZero and Turnitin | HumanizeIt",
    description:
      "Learn how students use HumanizeIt to make AI-assisted writing undetectable by GPTZero and Turnitin. Free plan available.",
    url: "https://humanizeit.app/use-cases/students",
    type: "website",
  },
  alternates: {
    canonical: "https://humanizeit.app/use-cases/students",
  },
};

const h2Style = {
  fontFamily: THEME.fontHeading,
  fontWeight: 700,
  color: THEME.text,
  fontSize: "24px",
  marginTop: "40px",
  marginBottom: "16px",
  letterSpacing: "-0.01em",
};

const pStyle = {
  color: THEME.textDim,
  lineHeight: 1.75,
  marginBottom: "16px",
  fontSize: "16px",
};

export default function StudentsUseCasePage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      {/* Breadcrumb */}
      <nav className="text-sm mb-8" style={{ color: THEME.textDim }}>
        <Link href="/" className="hover:underline">
          Home
        </Link>
        {" > "}
        <span>Use Cases</span>
        {" > "}
        <span>Students</span>
      </nav>

      <div className="kicker" style={{ marginBottom: "16px" }}>For students</div>
      <h1
        style={{
          fontFamily: THEME.fontHeading,
          fontWeight: 800,
          color: THEME.text,
          fontSize: "clamp(28px, 5vw, 38px)",
          letterSpacing: "-0.02em",
          marginBottom: "24px",
          lineHeight: 1.15,
        }}
      >
        HumanizeIt for Students: Make Your AI-Assisted Writing{" "}
        <span style={{ color: THEME.brand }}>Undetectable</span>
      </h1>

      {/* Disclaimer */}
      <div
        className="rounded-lg p-4"
        style={{
          marginBottom: "24px",
          background: THEME.warnDim,
          border: `1px solid ${THEME.warn}`,
        }}
      >
        <p style={{ ...pStyle, marginBottom: 0, fontWeight: 500, color: THEME.text }}>
          <strong style={{ color: THEME.warn }}>Disclaimer:</strong> HumanizeIt is designed to help students improve their writing skills and learn to
          write more naturally. Always follow your institution&apos;s academic integrity policies. Use responsibly.
        </p>
      </div>

      <p style={pStyle}>
        If you&apos;re a student in 2026, you already know the reality: AI tools like ChatGPT and Claude have become
        indispensable research and writing companions. They help you brainstorm ideas, outline arguments, overcome
        writer&apos;s block, and understand complex topics faster than ever before. But there&apos;s a growing problem
        that thousands of students face every single day — AI detectors are flagging your work, even when you&apos;ve
        done the hard thinking yourself.
      </p>

      <h2 style={h2Style}>The Problem: AI Detectors Are Punishing Honest Students</h2>
      <p style={pStyle}>
        Universities and schools around the world have adopted AI detection tools like GPTZero, Turnitin&apos;s AI
        writing detector, and Originality.ai. These tools scan submitted assignments and flag text they believe was
        generated by AI. The issue? They&apos;re far from perfect. False positives are rampant. Students who use AI as a
        learning aid — to help structure their thoughts or improve their grammar — are being accused of academic
        dishonesty. The consequences can be devastating: failed assignments, academic probation, or even expulsion.
      </p>
      <p style={pStyle}>
        Even students who write entirely from scratch sometimes get flagged. Modern AI detectors look for statistical
        patterns in word choice, sentence structure, and text predictability. If your natural writing style happens to
        align with those patterns, you could be falsely accused. It&apos;s an unfair system, and students deserve a
        solution.
      </p>

      <h2 style={h2Style}>How GPTZero and Turnitin Detect AI-Written Text</h2>
      <p style={pStyle}>
        Understanding how these tools work is the first step to beating them. GPTZero analyzes two key metrics:
        &quot;perplexity&quot; (how surprising the word choices are) and &quot;burstiness&quot; (the variation in
        sentence length and complexity). AI-generated text tends to be uniformly smooth and predictable, while human
        writing naturally varies in rhythm and complexity.
      </p>
      <p style={pStyle}>
        Turnitin&apos;s AI detection works similarly but operates at the sentence level, scoring each sentence
        individually and then calculating an overall AI probability for the document. It looks for the telltale
        uniformity that large language models produce — consistent tone, predictable transitions, and a lack of the
        &quot;messiness&quot; that characterizes authentic human writing.
      </p>

      <h2 style={h2Style}>How HumanizeIt Solves This</h2>
      <p style={pStyle}>
        HumanizeIt was built specifically to address this problem. The process is simple: paste your text into the
        editor, choose your humanization level (Light, Medium, or Aggressive), and click &quot;Humanize.&quot; Within
        seconds, you&apos;ll receive a rewritten version of your text that reads naturally and passes AI detection tools
        with flying colors.
      </p>
      <p style={pStyle}>
        The Light setting makes subtle adjustments — varying sentence structure, introducing natural imperfections, and
        adjusting word choices to increase perplexity scores. The Medium setting goes further, restructuring paragraphs
        and injecting more human-like phrasing. The Aggressive setting completely rewrites the text while preserving your
        core arguments and meaning, producing output that is virtually indistinguishable from text written entirely by
        hand.
      </p>

      <h2 style={h2Style}>Why HumanizeIt Is Different</h2>
      <p style={pStyle}>
        Unlike cheap paraphrasing tools that simply swap out synonyms (often producing awkward, nonsensical sentences),
        HumanizeIt uses advanced language models specifically trained to produce natural, human-sounding prose. It
        preserves your meaning, your argument structure, and your voice. The output doesn&apos;t just dodge AI detectors
        — it actually reads better. Many students tell us that HumanizeIt has helped them understand what natural,
        engaging academic writing looks like, improving their own skills in the process.
      </p>
      <p style={pStyle}>
        We regularly test our output against GPTZero, Turnitin, Originality.ai, and other popular detection tools. Our
        Aggressive mode achieves a 99%+ pass rate across all major detectors. And because we update our models
        continuously, we stay ahead of detection algorithm updates.
      </p>

      <h2 style={h2Style}>Free Plan: Perfect for Students on a Budget</h2>
      <p style={pStyle}>
        We know students aren&apos;t exactly swimming in cash. That&apos;s why HumanizeIt offers a generous free plan
        that lets you humanize up to 3 documents per day at no cost. It&apos;s enough for most homework assignments and
        short essays. Need more? Our student-friendly pricing means you can upgrade without breaking the bank. But for
        many students, the free plan is all they&apos;ll ever need.
      </p>

      <h2 style={h2Style}>Tips for Responsible Use</h2>
      <p style={pStyle}>
        We encourage students to use HumanizeIt as part of a responsible writing workflow. Start by doing your own
        research and forming your own arguments. Use AI tools to help you draft and refine — not to replace your
        thinking. Then run your text through HumanizeIt to ensure it reads naturally and won&apos;t be falsely flagged.
        Finally, always review the output yourself. Make sure it accurately represents your ideas and meets your
        assignment requirements.
      </p>
      <p style={pStyle}>
        Think of HumanizeIt as a writing polish, not a writing replacement. The best results come from students who
        engage with their material and use our tool to ensure their hard work is presented in the most natural,
        human-sounding way possible.
      </p>

      {/* CTA Box */}
      <div
        className="rounded-2xl p-8 text-center"
        style={{
          marginTop: "48px",
          background: THEME.surface1,
          border: `1px solid ${THEME.border}`,
          boxShadow: glow(THEME.brand, 0.18),
        }}
      >
        <h2 style={{ fontFamily: THEME.fontHeading, fontWeight: 700, fontSize: "24px", marginBottom: "12px", color: THEME.text, letterSpacing: "-0.02em" }}>
          Start Humanizing Your Writing for Free
        </h2>
        <p style={{ fontSize: "16px", lineHeight: 1.75, marginBottom: "24px", color: THEME.textDim }}>
          Our Free plan gives you 3 documents per day — no credit card required. Perfect for students who need reliable
          AI-detection-proof writing without spending a dime.
        </p>
        <Link
          href="/sign-up"
          className="inline-block font-bold rounded-full px-8 py-3 transition"
          style={{ background: THEME.gradient, color: "#ffffff", boxShadow: glow(THEME.brand, 0.36) }}
        >
          Sign Up Free &rarr;
        </Link>
      </div>
    </div>
  );
}
