import Link from "next/link";
import type { Metadata } from "next";
import { THEME, glow } from "@/lib/theme";

export const metadata: Metadata = {
  title: "AI Humanizer for Students: Avoid False AI Flags | HumanizeIt",
  description:
    "How students use HumanizeIt to check their own writing for AI-like patterns, avoid false GPTZero and Turnitin flags, and polish drafts within school rules.",
  keywords: [
    "AI humanizer for students",
    "humanize AI text",
    "GPTZero false positive",
    "Turnitin false positive",
    "AI detector for students",
    "check essay for AI",
    "student AI writing",
    "AI text humanizer",
  ],
  openGraph: {
    title: "AI Humanizer for Students: Avoid False AI Flags | HumanizeIt",
    description:
      "Check your own writing for the patterns AI detectors flag, avoid false GPTZero and Turnitin flags, and polish drafts within your school's rules.",
    url: "https://humanizeit.app/use-cases/students",
    type: "website",
  },
  alternates: {
    canonical: "https://humanizeit.app/use-cases/students",
  },
};

const h2Style = {
  fontFamily: THEME.fontHeading,
  fontWeight: 700,
  color: THEME.text,
  fontSize: "24px",
  marginTop: "40px",
  marginBottom: "16px",
  letterSpacing: "-0.01em",
};

const pStyle = {
  color: THEME.textDim,
  lineHeight: 1.75,
  marginBottom: "16px",
  fontSize: "16px",
};

export default function StudentsUseCasePage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      {/* Breadcrumb */}
      <nav className="text-sm mb-8" style={{ color: THEME.textDim }}>
        <Link href="/" className="hover:underline">
          Home
        </Link>
        {" > "}
        <Link href="/use-cases" className="hover:underline">
          Use Cases
        </Link>
        {" > "}
        <span>Students</span>
      </nav>

      <div className="kicker" style={{ marginBottom: "16px" }}>For students</div>
      <h1
        style={{
          fontFamily: THEME.fontHeading,
          fontWeight: 800,
          color: THEME.text,
          fontSize: "clamp(28px, 5vw, 38px)",
          letterSpacing: "-0.02em",
          marginBottom: "24px",
          lineHeight: 1.15,
        }}
      >
        HumanizeIt for Students: Protect Your Own Writing From{" "}
        <span style={{ color: THEME.brand }}>False AI Flags</span>
      </h1>

      {/* Disclaimer */}
      <div
        className="rounded-lg p-4"
        style={{
          marginBottom: "24px",
          background: THEME.warnDim,
          border: `1px solid ${THEME.warn}`,
        }}
      >
        <p style={{ ...pStyle, marginBottom: 0, fontWeight: 500, color: THEME.text }}>
          <strong style={{ color: THEME.warn }}>Disclaimer:</strong> HumanizeIt is for checking and polishing writing that is your own.
          Using it to hand in work you didn&apos;t write breaks our{" "}
          <Link href="/terms" style={{ color: THEME.brandHi }}>Terms of Service</Link> and most academic integrity
          policies. Always follow your institution&apos;s rules on AI tools.
        </p>
      </div>

      <p style={pStyle}>
        If you&apos;re a student in 2026, you already know the reality: AI tools like ChatGPT and Claude have become
        indispensable research and writing companions. They help you brainstorm ideas, outline arguments, overcome
        writer&apos;s block, and understand complex topics faster than ever before. But there&apos;s a growing problem
        for students — AI detectors can flag your work even when you wrote it yourself.
      </p>

      <h2 style={h2Style}>The Problem: AI Detectors Are Punishing Honest Students</h2>
      <p style={pStyle}>
        Universities and schools around the world have adopted AI detection tools like GPTZero, Turnitin&apos;s AI
        writing detector, and Originality.ai. These tools scan submitted assignments and flag text they believe was
        generated by AI. The issue? They&apos;re far from perfect, and false positives are well documented. A 2023
        Stanford study found that seven popular detectors labeled, on average, more than half of a set of essays written
        by non-native English speakers as AI-generated. Students who write plainly, follow a strict template, or got
        help with grammar can end up accused of misconduct, and the consequences can be serious: failed assignments,
        academic probation, or worse.
      </p>
      <p style={pStyle}>
        Even students who write entirely from scratch sometimes get flagged. Modern AI detectors look for statistical
        patterns in word choice, sentence structure, and text predictability. If your natural writing style happens to
        align with those patterns, you could be falsely accused. That&apos;s why it pays to check your own work
        before you submit it, and to keep evidence of how you wrote it.
      </p>

      <h2 style={h2Style}>How GPTZero and Turnitin Detect AI-Written Text</h2>
      <p style={pStyle}>
        Understanding how these tools work is the first step to understanding a flag, and to defending your work if
        it&apos;s ever questioned. GPTZero is best known for two metrics:
        &quot;perplexity&quot; (how surprising the word choices are) and &quot;burstiness&quot; (the variation in
        sentence length and complexity). AI-generated text tends to be uniformly smooth and predictable, while human
        writing naturally varies in rhythm and complexity.
      </p>
      <p style={pStyle}>
        Turnitin&apos;s AI detection works similarly but operates at the sentence level, scoring each sentence
        individually and then calculating an overall AI probability for the document. It looks for the telltale
        uniformity that large language models produce — consistent tone, predictable transitions, and a lack of the
        &quot;messiness&quot; that characterizes authentic human writing. Since August 2025 it also looks for text that
        has been run through AI humanizers, so a humanizer is not a way to slip AI-written work past it — and it
        shouldn&apos;t be.
      </p>

      <h2 style={h2Style}>How HumanizeIt Helps</h2>
      <p style={pStyle}>
        Start with the free{" "}
        <Link href="/ai-detector" style={{ color: THEME.brandHi }}>AI detector</Link>: paste your draft and see which
        patterns might make it read as AI-written — repetitive sentence openers, stock transitions, uniform sentence
        length, and so on. Every flag is named, so you know exactly what to look for in your draft.
      </p>
      <p style={pStyle}>
        If a passage of your own writing reads stiffly, you can edit it yourself or let the humanizer suggest a more
        natural version at a Light, Medium, or Heavy rewrite level. Light makes subtle adjustments to sentence rhythm and
        word choice; Medium restructures more; Heavy rewrites the most while aiming to keep your argument and meaning.
        Always read the result and keep what still sounds like you.
      </p>

      <h2 style={h2Style}>Why HumanizeIt Is Different</h2>
      <p style={pStyle}>
        Unlike cheap paraphrasing tools that simply swap out synonyms (often producing awkward, nonsensical sentences),
        HumanizeIt pairs a large language model with our own pattern analysis, so rewrites target the specific signals
        in your text instead of shuffling words at random. And because every flagged pattern is explained, the tool
        also shows you what natural, varied writing looks like — which helps your own writing over time.
      </p>
      <p style={pStyle}>
        What we won&apos;t do is promise you a score. No tool can guarantee how GPTZero, Turnitin, or any other detector
        will rate a piece of writing, and detectors change their models often. Anyone advertising a fixed &quot;pass
        rate&quot; is selling certainty that doesn&apos;t exist.
      </p>

      <h2 style={h2Style}>If Your Own Work Gets Flagged</h2>
      <p style={pStyle}>
        A detector score is an indicator, not proof — Turnitin itself says its AI score shouldn&apos;t be the sole basis
        for action against a student. If you&apos;re questioned about work you wrote, stay calm and show your process:
        your drafts and version history (Google Docs and Word both have one), your notes and outline, and the sources you
        used. Offer to talk through your argument. Our guide to{" "}
        <Link href="/faq/can-turnitin-detect-chatgpt" style={{ color: THEME.brandHi }}>how Turnitin detects AI</Link>{" "}
        explains what its score does and doesn&apos;t mean.
      </p>

      <h2 style={h2Style}>Free Plan: Perfect for Students on a Budget</h2>
      <p style={pStyle}>
        We know students aren&apos;t exactly swimming in cash. The{" "}
        <Link href="/ai-detector" style={{ color: THEME.brandHi }}>AI detector</Link> is free with no signup, the{" "}
        <Link href="/free-ai-humanizer" style={{ color: THEME.brandHi }}>free humanizer</Link> handles short passages
        without an account, and the free plan gives you 500 words a day — no credit card required. If you need more,
        Pro is $9 a month.
      </p>

      <h2 style={h2Style}>Tips for Responsible Use</h2>
      <p style={pStyle}>
        We encourage students to use HumanizeIt as part of a responsible writing workflow. Start by doing your own
        research and forming your own arguments. Use AI tools only in the ways your course allows — to brainstorm or
        check grammar, not to replace your thinking. Then check your draft for the patterns that commonly trigger false
        flags, and review any suggested rewrite yourself. Make sure it accurately represents your ideas and meets your
        assignment requirements.
      </p>
      <p style={pStyle}>
        Think of HumanizeIt as a writing polish, not a writing replacement. The best results come from students who
        engage with their material and use our tool to ensure their hard work is presented in the most natural,
        human-sounding way possible.
      </p>

      {/* CTA Box */}
      <div
        className="rounded-2xl p-8 text-center"
        style={{
          marginTop: "48px",
          background: THEME.surface1,
          border: `1px solid ${THEME.border}`,
          boxShadow: glow(THEME.brand, 0.18),
        }}
      >
        <h2 style={{ fontFamily: THEME.fontHeading, fontWeight: 700, fontSize: "24px", marginBottom: "12px", color: THEME.text, letterSpacing: "-0.02em" }}>
          Check Your Writing Before You Submit
        </h2>
        <p style={{ fontSize: "16px", lineHeight: 1.75, marginBottom: "24px", color: THEME.textDim }}>
          Paste your draft into the free AI detector to see which patterns could get it flagged — no signup, no credit
          card.
        </p>
        <Link
          href="/ai-detector"
          className="inline-block font-bold rounded-full px-8 py-3 transition"
          style={{ background: THEME.gradient, color: "#ffffff", boxShadow: glow(THEME.brand, 0.36) }}
        >
          Check My Writing Free &rarr;
        </Link>
      </div>
    </div>
  );
}
