import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { Suspense } from "react";
import { Providers } from "./providers";
import { PostHogPageview } from "@/components/posthog-pageview";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "HumanizeIt — Detect & Humanize AI Text",
  description: "Score your text against 24 AI detection patterns and rewrite it to sound 100% human. Free to start.",
  metadataBase: new URL("https://humanizeit.app"),
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/favicon.svg", type: "image/svg+xml" },
    ],
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  openGraph: {
    title: "HumanizeIt — Detect & Humanize AI Text",
    description: "Score your text against 24 AI detection patterns and rewrite it to sound 100% human.",
    url: "https://humanizeit.app",
    siteName: "HumanizeIt",
    type: "website",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "HumanizeIt — Detect & Humanize AI Text",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "HumanizeIt — Detect & Humanize AI Text",
    description: "Score your text against 24 AI detection patterns and rewrite it to sound 100% human.",
    images: ["/og-image.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: "https://humanizeit.app",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <head>
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "WebApplication",
                name: "HumanizeIt",
                url: "https://humanizeit.app",
                description:
                  "Detect AI-generated text with 24 pattern analysis and humanize it to pass GPTZero, Turnitin, and Originality.ai",
                applicationCategory: "WritingApplication",
                operatingSystem: "Web",
                offers: [
                  {
                    "@type": "Offer",
                    name: "Free",
                    price: "0",
                    priceCurrency: "USD",
                  },
                  {
                    "@type": "Offer",
                    name: "Pro",
                    price: "9",
                    priceCurrency: "USD",
                  },
                  {
                    "@type": "Offer",
                    name: "Team",
                    price: "29",
                    priceCurrency: "USD",
                  },
                ],
              }),
            }}
          />
          <script
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "FAQPage",
                mainEntity: [
                  {
                    "@type": "Question",
                    name: "What is HumanizeIt?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "HumanizeIt is a tool that detects AI-generated patterns in your text and rewrites it to sound naturally human, helping you bypass AI detectors.",
                    },
                  },
                  {
                    "@type": "Question",
                    name: "How does AI detection work?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "HumanizeIt analyzes 24 patterns including sentence entropy, vocabulary diversity, burstiness, and syntactic variation to determine if text was generated by AI.",
                    },
                  },
                  {
                    "@type": "Question",
                    name: "Will my text pass GPTZero?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "HumanizeIt scores your text against the same patterns GPTZero uses and rewrites flagged sections so your text reads as human-written.",
                    },
                  },
                  {
                    "@type": "Question",
                    name: "Is HumanizeIt free?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "Yes! The free tier includes 500 words per day. Pro is $9/month for 50,000 words/month with priority processing.",
                    },
                  },
                  {
                    "@type": "Question",
                    name: "How accurate is the AI detector?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "HumanizeIt uses 24 proprietary detection patterns and achieves over 90% accuracy on GPT-4 generated text.",
                    },
                  },
                  {
                    "@type": "Question",
                    name: "Does it work with ChatGPT text?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "Yes, HumanizeIt is optimized for text from GPT-3.5, GPT-4, Claude, Gemini, and other major AI models.",
                    },
                  },
                  {
                    "@type": "Question",
                    name: "Is my text stored?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "No. Your text is never stored. It is processed entirely in memory and discarded immediately after analysis.",
                    },
                  },
                  {
                    "@type": "Question",
                    name: "What AI detectors does it bypass?",
                    acceptedAnswer: {
                      "@type": "Answer",
                      text: "HumanizeIt helps bypass GPTZero, Turnitin, Originality.ai, Copyleaks, and ZeroGPT by rewriting text to match human writing patterns.",
                    },
                  },
                ],
              }),
            }}
          />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Providers>
            <Suspense fallback={null}>
              <PostHogPageview />
            </Suspense>
            {children}
          </Providers>
          <Toaster richColors position="bottom-center" />
          <Analytics />
          <SpeedInsights />
        </body>
      </html>
    </ClerkProvider>
  );
}
