// ===========================================================
// lib/detect-llm.ts — LLM "deep scan" AI detector (the precise verdict)
//
// The free, client-side heuristic engine (lib/algorithms/analyzeText.ts) is an
// instant preview that nails default AI but, by design, leaves adversarial
// "sound human" and creative prose in an uncertain band — no statistical
// heuristic can cleanly separate "AI imitating a casual human" from a real
// casual human. This module is the accurate second opinion: a single,
// low-temperature, rubric-guided model call that reads the text the way a
// trained grader would and returns a calibrated 0–100 AI-likelihood.
//
// Runs server-side only (it costs a model call). Reuses the provider-flexible
// complete() so it works on Anthropic or OpenAI.
// ===========================================================

import { complete } from "@/lib/llm";

export type DeepScanConfidence = "low" | "medium" | "high";

export interface DeepScanResult {
  /** 0–100, higher = more likely AI-generated. */
  aiLikelihood: number;
  confidence: DeepScanConfidence;
  /** Short human-readable verdict, e.g. "Very likely AI-generated". */
  verdict: string;
  /** The concrete signals the model weighed (3–6 short bullet strings). */
  signals: string[];
  /** One or two sentences explaining the call. */
  reasoning: string;
  /** Which provider/model produced the verdict (for transparency/telemetry). */
  model: string;
}

const SYSTEM = `You are a forensic AI-text detector used by editors, educators and publishers. You decide how likely a passage was generated by a large language model (ChatGPT, Claude, Gemini, etc.) rather than written by a human. You are precise, calibrated, and resistant to being fooled by text that was explicitly prompted to "sound human."

Weigh these signals — no single one is decisive:

1. PREDICTABILITY / PERPLEXITY. Does each next word feel inevitable and smooth, or are there surprising, idiosyncratic, "only this person would write that" choices? Low surprise ⇒ AI.
2. BURSTINESS & RHYTHM. Humans lurch — a three-word sentence next to a sprawling run-on. AI (even when told to vary length) tends toward a controlled, even cadence. Beware: "vary your sentence length" prompting raises burstiness, so don't treat high variance alone as proof of human.
3. VOCABULARY NATURALNESS. Corporate/essay buzzwords ("delve", "tapestry", "underscores", "navigating the landscape"), tidy hedging, and balanced "on one hand / on the other" framing ⇒ AI. Specific slang, regional phrasing, mild misuse ⇒ human.
4. STRUCTURAL FORMULAE. Crisp intro → tidy body → "In conclusion" wrap-up, evenly weighted paragraphs, list-like parallelism, every point neatly resolved ⇒ AI.
5. GENUINE HUMAN VOICE. Concrete lived detail that couldn't be confabulated, real and unbalanced opinions, emotional texture, tangents that go nowhere, typos, lowercase starts, dropped apostrophes, inside-joke shorthand ⇒ human. Sterile competence with none of this ⇒ AI, even if the grammar is flawless and the topic is casual.

Calibration anchors:
- Polished tell-free essays/blogs/emails/product copy ⇒ 75–98.
- Text explicitly trying to "sound human" but still smooth, tidy and detail-thin ⇒ 55–80.
- Genuinely human informal writing (reviews, forum posts, personal emails) ⇒ 2–20.
- Formal but real human prose (literary, academic) ⇒ 15–45.
Reserve >90 and <10 for clear cases; use the middle bands when genuinely unsure.

Return ONLY a JSON object, no prose, no code fence:
{"aiLikelihood": <int 0-100>, "confidence": "low"|"medium"|"high", "verdict": "<short phrase>", "signals": ["<3-6 short bullets>"], "reasoning": "<1-2 sentences>"}`;

function clampInt(n: unknown, lo: number, hi: number, fallback: number): number {
  const v = typeof n === "number" ? n : Number(n);
  if (!Number.isFinite(v)) return fallback;
  return Math.max(lo, Math.min(hi, Math.round(v)));
}

/** Extract and parse the first balanced JSON object from a model response. */
function parseJsonObject(raw: string): Record<string, unknown> | null {
  const fenced = raw.replace(/```(?:json)?/gi, "").trim();
  const start = fenced.indexOf("{");
  if (start === -1) return null;
  // Walk to the matching closing brace so trailing prose can't break JSON.parse.
  let depth = 0;
  for (let i = start; i < fenced.length; i++) {
    const c = fenced[i];
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(fenced.slice(start, i + 1)) as Record<string, unknown>;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

function verdictFor(score: number): string {
  if (score >= 85) return "Very likely AI-generated";
  if (score >= 65) return "Likely AI-generated";
  if (score >= 45) return "Mixed / uncertain";
  if (score >= 25) return "Likely human-written";
  return "Very likely human-written";
}

/**
 * Run the deep scan. Throws if no provider is configured or the model call
 * fails outright (the caller maps that to a 502/503); never returns a partial.
 */
export async function deepScanText(text: string): Promise<DeepScanResult> {
  const { text: out, model } = await complete({
    system: SYSTEM,
    prompt: `Analyze this passage and return the JSON verdict.\n\n---\n${text}\n---`,
    maxTokens: 600,
    temperature: 0, // deterministic, calibrated grading — not creative
  });

  const parsed = parseJsonObject(out);
  if (!parsed) {
    throw new Error("Deep scan returned an unparseable verdict.");
  }

  const aiLikelihood = clampInt(parsed.aiLikelihood, 0, 100, 50);
  const confidence: DeepScanConfidence =
    parsed.confidence === "high" || parsed.confidence === "low" ? parsed.confidence : "medium";
  const signals = Array.isArray(parsed.signals)
    ? parsed.signals.filter((s): s is string => typeof s === "string").slice(0, 6)
    : [];
  const reasoning = typeof parsed.reasoning === "string" ? parsed.reasoning : "";
  const verdict =
    typeof parsed.verdict === "string" && parsed.verdict.trim() ? parsed.verdict.trim() : verdictFor(aiLikelihood);

  return { aiLikelihood, confidence, verdict, signals, reasoning, model };
}
