import Link from "next/link";
import type { Metadata } from "next";
import { kitStyles, Breadcrumbs, FaqSection, PageCta } from "@/components/seo/page-kit";
import { THEME } from "@/lib/theme";

const URL = "https://humanizeit.app/faq";

export const metadata: Metadata = {
  title: "AI Detection FAQ: Humanizing, Detectors, and Ethics",
  description:
    "An AI detection FAQ covering how detectors work, whether AI text can be humanized, what counts as ethical use, free tools, and which checkers flag ChatGPT and Claude.",
  keywords: [
    "AI detection FAQ",
    "AI humanizer FAQ",
    "can AI detectors be wrong",
    "humanize AI text",
    "bypass AI detection",
    "ChatGPT detection",
    "free AI humanizer",
    "is humanizing AI cheating",
  ],
  openGraph: {
    title: "AI Detection FAQ: Humanizing, Detectors, and Ethics",
    description:
      "An AI detection FAQ covering how detectors work, whether AI text can be humanized, what counts as ethical use, free tools, and which checkers flag ChatGPT and Claude.",
    url: URL,
    siteName: "HumanizeIt",
    type: "website",
  },
  alternates: {
    canonical: URL,
  },
};

const detectorLink = {
  color: THEME.brandHi,
  fontWeight: 600,
  textDecoration: "none",
};

export default function FaqHubPage() {
  return (
    <div style={{ maxWidth: "48rem", margin: "0 auto", padding: "40px 16px" }}>
      <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "FAQ" }]} />

      <div className="kicker" style={{ marginBottom: "14px" }}>Help center</div>

      <h1 style={kitStyles.h1}>AI Detection &amp; Humanizing: FAQ</h1>

      <p style={{ ...kitStyles.p, fontSize: "17px" }}>
        AI detection is a confusing topic, and most of the confusion comes from treating detector
        scores as facts rather than estimates. This FAQ answers the questions people actually ask
        before they trust a tool with their writing: how detectors decide what looks &quot;AI,&quot;
        whether you can change that, where the ethical line sits, and which checkers tend to flag
        which models. If you want to experiment while you read, you can run text through our free{" "}
        <Link href="/ai-detector" style={{ color: THEME.brandHi }}>AI detector</Link> or rewrite a
        draft with the{" "}
        <Link href="/free-ai-humanizer" style={{ color: THEME.brandHi }}>free AI humanizer</Link>.
      </p>

      <h2 style={kitStyles.h2}>Start here: the short version</h2>
      <p style={kitStyles.p}>
        AI detectors look at statistical patterns in your text &mdash; mainly how predictable each
        word is and how much your sentences vary in length and complexity &mdash; and report a
        probability that the writing came from a language model. That probability is a useful signal,
        but it is not proof of authorship, and the detector vendors themselves say so. Humanizing is
        the process of rewriting text so it recovers the natural variation human writing has, which
        lowers how AI-like it reads. None of this guarantees a particular score on every detector,
        because each one is trained differently and updated on its own schedule.
      </p>

      <FaqSection
        heading="Common questions"
        faqs={[
          {
            q: "What is an AI detector and how does it work?",
            a: "An AI detector is a classifier trained to estimate the probability that a piece of text was generated by a language model. Most rely on two signals: perplexity (how surprising each word is given the words before it) and burstiness (how much sentence length and complexity vary). Model output tends to be smooth and predictable, so low perplexity with little variation reads as 'AI-like.' The output is a probability, not a verdict. To see how a specific tool behaves, you can read our walkthrough of how AI detection works.",
          },
          {
            q: "Are AI detectors accurate, or can they be wrong?",
            a: "They are estimators and they can be wrong in both directions. False positives &mdash; human writing flagged as AI &mdash; are well documented, especially on short, formal, or templated text, and the detector vendors include disclaimers acknowledging this. False negatives happen too, where edited AI text reads as human. Treat any score as input to a judgment rather than a final answer, and never assume two different detectors will agree on the same passage.",
          },
          {
            q: "Can AI-generated text actually be humanized?",
            a: "Yes, in the sense that you can rewrite text so word choice and sentence rhythm vary the way human writing naturally does, which lowers how AI-like it reads to a given detector. What you cannot do is guarantee a clean score everywhere forever. Detectors retrain, each weights its signals differently, and a passage that clears one tool may still flag on a stricter one. Think of humanizing as reducing risk and improving readability, not as a permanent cloak.",
          },
          {
            q: "Is using an AI humanizer cheating?",
            a: "It depends entirely on what you are doing and what rules apply. Using a humanizer to keep your own writing from being falsely flagged, or to make AI-assisted drafting read more naturally, is reasonable. Passing off generated work as your own where that is forbidden is not, regardless of the tool. We build tools that explain how detection works and improve how text reads; we do not encourage violating your school's or employer's academic-integrity and conduct policies. Always follow them.",
          },
          {
            q: "Will humanizing change the meaning of my text?",
            a: "A good humanizer rephrases for natural variation while preserving your argument, facts, and structure &mdash; but no automated rewrite is perfect. You should always read the output before using it to confirm it still says what you intended and has not introduced errors. This matters most in technical, cited, or data-heavy passages, where a small rephrasing can quietly change a claim.",
          },
          {
            q: "Why does one detector flag my text while another clears it?",
            a: "Each tool was trained on different data, classifies at a different level (whole-document versus sentence-by-sentence), and sets its threshold in a different place. A passage that looks borderline to a strict tool can read as clean to a lenient one. That is why a single 'pass' is not portable, and why it helps to check against the specific detector that matters for your situation rather than a random free checker.",
          },
          {
            q: "Is there a genuinely free way to check and humanize text?",
            a: "Yes. You can paste text into our free AI detector to see how it scores, and rewrite drafts with the free AI humanizer without paying. Free tiers exist to let you evaluate quality before committing; heavier or longer-form use is where paid plans come in. Be cautious with any free tool that promises a guaranteed 'undetectable' result &mdash; that claim cannot hold across every detector and every update.",
          },
          {
            q: "Does humanizing remove plagiarism or replace citations?",
            a: "No. Humanizing changes phrasing and rhythm; it does not check sources, verify facts, or add citations. AI detection and plagiarism detection are separate problems &mdash; some tools (like Originality.ai and Copyleaks) bundle both, but a clean AI score says nothing about whether your sources are properly credited. If your work needs citations, add and verify them yourself.",
          },
          {
            q: "Do detectors get better over time, and does that affect old results?",
            a: "Yes. Detectors retrain as new models appear, so a result you got last month is a snapshot, not a guarantee. Text that read as human to an older version can be re-scored differently after an update, and vice versa. This is the single most important reason to treat any detector score &mdash; clean or flagged &mdash; as temporary and contextual rather than absolute.",
          },
          {
            q: "What is the safest way to use AI in my writing workflow?",
            a: "Start from work you actually own: do your own research, form your own arguments, and use AI to draft or refine rather than to replace your thinking. Then check the result against the detector that matters to you, rewrite passages that read as flat or mechanical, and review the final output yourself. The goal is honest writing that reads naturally, not gaming a number.",
          },
        ]}
      />

      <h2 style={kitStyles.h2}>Detector and model questions</h2>
      <p style={kitStyles.p}>
        Some questions are too specific for a one-line answer because they depend on a particular
        detector and a particular model. The pages below dig into the most common pairings &mdash;
        what each detector is actually looking for, how reliably it flags a given model, and how to
        read its result. Start with whichever combination applies to you.
      </p>
      <p style={kitStyles.p}>
        <Link href="/faq/can-turnitin-detect-chatgpt" style={detectorLink}>
          Can Turnitin detect ChatGPT? &rarr;
        </Link>
        <br />
        <Link href="/faq/can-turnitin-detect-claude" style={detectorLink}>
          Can Turnitin detect Claude? &rarr;
        </Link>
        <br />
        <Link href="/faq/can-gptzero-detect-chatgpt" style={detectorLink}>
          Can GPTZero detect ChatGPT? &rarr;
        </Link>
      </p>
      <p style={kitStyles.p}>
        The short, honest answer to all three is &quot;sometimes, with a probability, not a
        certainty.&quot; Turnitin and GPTZero both look for the statistical smoothness that models
        produce, so unedited output is more likely to be flagged than text you have genuinely
        reworked. None of them can read your mind or prove who wrote a sentence; they estimate. The
        linked pages explain the nuances per detector so you can interpret a flag instead of panicking
        at it.
      </p>

      <h2 style={kitStyles.h2}>Where to go next</h2>
      <p style={kitStyles.p}>
        If you want to understand a specific detector in depth &mdash; Turnitin, GPTZero, ZeroGPT,
        Originality.ai, Copyleaks, or Winston AI &mdash; the{" "}
        <Link href="/bypass" style={{ color: THEME.brandHi }}>bypass detection hub</Link> has a
        focused guide for each one, including how it scores text and what a flag actually means. For a
        broader conceptual primer, see{" "}
        <Link href="/blog/ai-detection-how-it-works" style={{ color: THEME.brandHi }}>how AI detection works</Link>.
      </p>
      <p style={kitStyles.p}>
        And if you just want to act on a draft right now: run it through the{" "}
        <Link href="/ai-detector" style={{ color: THEME.brandHi }}>AI detector</Link> to see how it
        scores, rewrite the parts that read as flat with the{" "}
        <Link href="/free-ai-humanizer" style={{ color: THEME.brandHi }}>free humanizer</Link>, then
        read the output yourself to make sure it still says exactly what you mean.
      </p>

      <PageCta
        heading="Check it, humanize it, re-check it"
        body="Paste your draft into the free AI detector to see how it scores, then humanize it to recover natural variation &mdash; no credit card required to start."
        href="/free-ai-humanizer"
        cta="Try the Free Humanizer"
      />
    </div>
  );
}
